// judge0-to-monaco.ts
export const judge0ToMonaco: Record<string, string> = {
  "C": "c",
  "C++": "cpp",
  "Java": "java",
  "Python": "python",
  "JavaScript": "javascript",
  "TypeScript": "typescript",
  "Go": "go",
  "PHP": "php",
  "C#": "csharp",
  "Swift": "swift",
  "Rust": "rust",
  "Ruby": "ruby",
  "SQL": "sql",
  "R": "r",
  "Kotlin": "kotlin",
  "Scala": "scala",
  "Perl": "perl",
  "Lua": "lua",
  "Haskell": "haskell",
  "Objective-C": "objective-c",
  "Bash": "shell",
  "COBOL": "plaintext",
  "Assembly": "plaintext",
  "Fortran": "plaintext",
  "Common Lisp": "plaintext",
  "Pascal": "plaintext",
  "Basic": "plaintext",
};
